[package]
name = "CandleChart"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { version = "0.14", features = ["canvas", "tokio"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
